- name: Ensure nginx is present or install it
  apt: 
    name: nginx 
    state: installed 
    update_cache: true

- name: Ensure rsync is present or install it
  apt: 
    name: rsync 
    state: installed 
    update_cache: true

# task 4
- name: Add webapp-data group
  group:
    name: webapp-data
    state: present

- name: Copy web-app files to /var/www 
  synchronize: 
    src: ../files/
    dest: /var/www
    rsync_opts: "--chown=www-data:webapp-data" # --chmod=g+rw
    archive: yes
  notify:
    - restart nginx

# - name: Set /var/wwww attributes
#   file:
#     path: /var/wwww/
#     owner: www-data
#     group: webapp-data
#     state: directory
#     recurse: yes
#     mode: 0660
